# Generated by Django 3.2.5 on 2022-10-09 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_accountstatus_user_name'),
        ('profiles', '0015_auto_20180423_0727'),
    ]

    operations = [
    ]
